### ISSUE TITLE
Twitter user profile URL incorrectly deobfuscates

### ISSUE THREAD

**Issue by cglmrfreeman** [AlttiRi/twitter-click-and-save#2]
Greetings,

As I discovered and filed in https://github.com/theAlinP/twitter-link-deobfuscator/issues/19,  profile URLs are deobfuscated incorrectly. The issue example used in the twitter-link-deobfuscator issue, [@Hitoimim](https://twitter.com/Hitoimim), produces the identical issue. [@INKBLOTo](https://twitter.com/INKBLOTo) also appends the deobfuscated link after http(s)://twitter.com, making the link not navigable without modification.

**Comment by AlttiRi** [comment]
Ah, wait, it's because of the script, I thought, that Twitter just works so.

Looks to be possible to fix, since the profile link element is located in unique `[data-testid="UserProfileHeader_Items"]` element.

**Comment by AlttiRi** [comment]
The oblivious bug is fixed: https://github.com/AlttiRi/twitter-click-and-save/commit/944bea828f139cbe621304b3166bed89683eaaa1 the link will work now in any case (as a direct link, or as a redirect one).

For long links it's not possible to recreate the original link _easy_, there is no information about the trimmed part of the link in HTML of the page.

_Probably_, it's possible to do with Twitter API (although I'm not familiar with it).

Also it possible to do by fetching information from https://nitter.net/ profile page, since it contains the non-trimmed original link, but it seems to be overkill even for a lazy-loaded feature.

**Comment by cglmrfreeman** [comment]
I do have access to and understand the api to grab user links and can elaborate if you'd like. I implemented the grab in python but I'm sure I can refind the documentation page that explains it in terms of raw api.

**Comment by AlttiRi** [comment]
DevTools is enough.

---

Fixed.

https://github.com/AlttiRi/twitter-click-and-save/commit/f685122d2f19e63ef6c5954df846208771321d11

**Comment by cglmrfreeman** [comment]
Great! Will give this new version a test in the morning and close out if I see everything working as intended. I have no doubts it works though as obviously you've tested it already!

**Comment by cglmrfreeman** [comment]
Oh ho! Yes! It is indeed fixed, fantastic! If I bump into any new situation I will reach out in this issue again. Thanks for all your hard work!
