### ISSUE TITLE
Twitter update new  style for "media"  , download button disappeared ...

### ISSUE THREAD

**Issue by honbit** [AlttiRi/twitter-click-and-save#36]
X's media panel update to display more information. 
Will there be an update to the program to support the new 'media' features?

**Comment by AlttiRi** [comment]
Well, it's no more just the filtered list of posts with media, but the list of thumbnails of posts with media. So, it does not work anymore.

Technically, it should be not difficult to add a button to download all medias of a tweet by a click.

However, I'm not sure how to be with the download history, since only one image is displayed at once.

**Comment by honbit** [comment]
Is it feasible to add a button to each thumbnail, allowing users to select their preferred images and then download them upon clicking?
I think the new 'Media' is just a change in the display format; the operational logic of the program can remain unchanged.

**Comment by AlttiRi** [comment]
It requires a new handler for new type of previews and the new logic for the post downloading, so it's not "2 min to fix CSS".
Okay, added a reminder to check it on weekends.

**Comment by AlttiRi** [comment]
Should be done in the dev version on GitHub.

The notable count of time I spend for refactoring of API response handling https://github.com/AlttiRi/twitter-click-and-save/commit/ca13374bcbe728ac2aa308fee72eb906aa550d27


Mostly looks like a dirty fix, ideally, I need to totally rewrite the core functional. https://github.com/AlttiRi/twitter-click-and-save/commit/cc58ed8844838cf84f09e3ad54df133166f00b2a, https://github.com/AlttiRi/twitter-click-and-save/commit/e395088fcce128808b1c084756b32f0e790e09cd

**Comment by honbit** [comment]
Great! Looking forward to your achievements.

Actually, I have an idea to store users' download history in a database and simultaneously download text corresponding to the images. 
This way, can program to reconstruct the timeline. 
However, this involves database installation, as well as cross- origin issues, and might also require installing Nginx, increasing the overall complexity. 
Do you have any suggestions for this idea?

**Comment by AlttiRi** [comment]
Technically, it's possible, nothing difficult, but it would be some hours spending for rewriting of some parts of the script.

>Nginx

It's a web server for hosting a static content.

[IndexedDB](https://developer.mozilla.org/ru/docs/Web/API/IndexedDB_API) is more than enough to store short text descriptions.

---

[I recommend](https://github.com/AlttiRi/twitter-click-and-save#gallery-dl-config) to use gallery-dl for bulk downloading.

In particularly, to download text descriptions.

Here is my gallery-dl config:
_`~/gallery-dl/config.json` (only a part for Twitter)_
```json
        "...": { "..." },

        "twitter": {
            "sleep": 0,
            "sleep-request": 1,
            "retweets": false,
            "directory": ["[gallery-dl]", "[{category}] {author[name]}"],
            "filename": "[{category}] {author[name]}—{date:%Y.%m.%d}—{retweet_id|tweet_id}—{filename}.{extension}",
            "fallback": false,
            "cards": false,
            "pinned": true,
            "replies": "self",
            "cookies": {
                "auth_token": "_________PUT_YOUR_COOKIE_HERE_________"
            },
            "text-tweets": false,
            "postprocessors": [{
                "name": "mtime",
                "event": "post"
            }, {
                "directory": "metadata",
                "filename": "[{category}] {author[name]}—{date:%Y.%m.%d}—{retweet_id|tweet_id}.html",
                "name": "metadata",
                "event": "post",
                "mtime": true,
                "mode": "custom",
                "archive": "~/gallery-dl/gallery-dl-postprocessors.sqlite",
                "archive-format": "{tweet_id}_{retweet_id}_p1",
                "content-format": "\fT ~/gallery-dl/templates/twitter.html",
                "format-old": "<div id='{retweet_id|tweet_id}'><h4><a href='https://twitter.com/{author[name]}/status/{retweet_id|tweet_id}'>{retweet_id|tweet_id}</a> by <a href='https://twitter.com/{author[name]}'>{author[name]}</a></h4><div class='content'>{content}</div><hr><div>{date:%Y.%m.%d %H:%M:%S}</div><hr></div><br>"
            }]
        },

        "...": { "..." },
```

It has a "metadata" postprocessor to write tweet's text in HTML files. One tweet — one HTML with the text.

HTML template:
`~/gallery-dl/templates/twitter.html`
```html
<div id="{retweet_id|tweet_id}">
  <h4>
    <a href="https://twitter.com/{author[name]}/status/{retweet_id|tweet_id}">{retweet_id|tweet_id}</a> by <a href="https://twitter.com/{author[name]}">{author[name]}</a>
  </h4>
  <div class="content">{content:?//R
/<br>/}</div>
  <hr>
  <div>{date:%Y.%m.%d %H:%M:%S}</div>
  <hr>
</div>
<br>
```

---

Why HTML?
It has a formatted representation. You only need a browser to open it.

Also, you can concatenate all HTML files _(for example, with a simple console command)_ into one file and it will work.
So, the result will contain all tweet's text content. 

Since it's open in a browser, it's possible to use JS for some work.

For example, I use my userscript https://github.com/AlttiRi/href-taker to parse all links from the result HTML file.

---

Also, use `-o text-tweets=true` console argument to prevent gallery-dl from skipping a post without media.

**Comment by AlttiRi** [comment]
For example, the result single HTML file _(created with gallery-dl's postprocessor)_ for [a tweet](https://twitter.com/CyberTemptation/status/1431579237031583745):

![Screenshot](https://github.com/AlttiRi/twitter-click-and-save/assets/16310547/541fa5fb-a307-403d-8d04-3708ed27c3cd)

It has a description as well as other meta information: `date`, `id`, the links to a tweet and a profile.

---

Here is a screenshot of all HTML files are concated into one file with the opened popup of my [HrefTaker](https://github.com/AlttiRi/href-taker) userscript to parse links _(`catbox` only on the screenshot)_ from all tweets:

![twitter-catbox-links-parsing](https://github.com/AlttiRi/twitter-click-and-save/assets/16310547/0fb31af5-da06-4f0e-bfa3-bac907453bde)

---

To concat HTML files I use a bash function is defined in `~/.bashrc` file:
```
alias catahtml=fun_cat_html

function fun_cat_html {
    current_date_time=$(date +"%Y.%m.%d-%H.%M.%S")
    cat *.html > "$TEMP/_temp-cat-html-result-$current_date_time.html";
    start "$TEMP/_temp-cat-html-result-$current_date_time.html";
    sleep 0;
    exit;
}
```
Just type `catahtml` in a [bash terminal](https://gitforwindows.org/), then the result file will be opened in your browser automatically.

**Comment by honbit** [comment]
Great! 
It looks like you already have a complete solution. I'll try your approach. 
Thanks for sharing!
