### ISSUE TITLE
Unable to grab image (pinned tweet)

### ISSUE THREAD

**Issue by cglmrfreeman** [AlttiRi/twitter-click-and-save#8]
This NSFW [tweet](https://twitter.com/kuzuaki/status/1557603299238748161) doesn't seem to want to play well with the script for some reason...

**Comment by AlttiRi** [comment]
Everything is OK with it for me, it's just a 2.11 MB image.

**Comment by AlttiRi** [comment]
From the profile page the same.

Maybe for some reason the original image was unavailable _for a time_. Now it's OK.

**Comment by cglmrfreeman** [comment]
Oh I suppose some actual data on this might help:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://pbs.twimg.com/media/FZ23OtiaIAAw81F?format=jpg&name=4096x4096. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 504.
Uncaught (in promise) Fallback URL failed Twitter Click'n'Save.user.js:470:27
    _imageClickHandler moz-extension://1e476ed0-0b6d-4fa3-b1ad-0c60c8f766f0/userscripts/Twitter Click'n'Save.user.js?id=39bdebad-11a6-474b-9e59-e15c8fbbf97f:470
    AsyncFunctionThrow self-hosted:673
```

**Comment by AlttiRi** [comment]
> Status code: 504.

I think that the image is just not available for your location for a time.

https://github.com/mikf/gallery-dl/issues/1881


Can you open this URLs _successfully_: 
- https://pbs.twimg.com/media/FZ23OtiaIAAw81F?format=jpg&name=4096x4096
- https://pbs.twimg.com/media/FZ23OtiaIAAw81F?format=jpg&name=orig

?

**Comment by cglmrfreeman** [comment]
Both the above links load just fine. Just _from_ the tweet itself doesn't work :thinking:

**Comment by AlttiRi** [comment]
Maybe Firefox just uses that cached response, which still contains 504 status code.

Twitter returns for status code 200 `access-control-allow-origin: *` header so it should not to be a CORS problem.

---

Yeah, possible it's because of `cache: "force-cache",`.
https://github.com/AlttiRi/twitter-click-and-save/blob/6cc1318d5d0ca03a0bccfa152580e766e974f0ae/twitter-click-and-save.user.js#L1242

I did not think that it can have a con like caching a response with non 200 status code.

**Comment by cglmrfreeman** [comment]
Well, it worked just before I updated and after, but hopefully this might help problems in the future, so I guess overall this was a success! Thanks much!
